add bookmark page & button that toggles isBookmarked
TariqAlQadi/capstone-project pull request #12
Opened 2023-01-24 13:13 UTC by TariqAlQadi

created bookmark page, button that toggles color and isBookmarked state

2023-01-24 13:35 UTC, SaschaRadojkovic commented on pages/_app.js
>      </SWRConfig>
how far i see there is only a closing </SWRConfig> and it is not warpping the component tag

2023-01-24 13:39 UTC, SaschaRadojkovic commented on pages/tutorials/index.js
>  import useSWR from "swr";
useSWR is imported but not used mabe you should remove it

2023-01-24 13:43 UTC, TariqAlQadi commented on pages/_app.js
>      </SWRConfig>
Hi Sascha 
have a closer look .. there's an opening tag aswell .. otherwise the application would not work 😇

2023-01-24 13:44 UTC, TariqAlQadi commented on pages/_app.js
>      </SWRConfig>
I just added the Navigation and the SWRConfig opening tag is not in view, because its above the Head component

2023-01-24 13:48 UTC, SaschaRadojkovic commented on pages/_app.js
>      </SWRConfig>
ah sorry i did not see that it was not visible ;)

2023-01-24 13:49 UTC, TariqAlQadi commented on pages/_app.js
>      </SWRConfig>
no problemo!

2023-01-24 15:39 UTC, doemser requested changes

2023-01-24 15:39 UTC, doemser commented on components/CardDetails/index.js
> +        )}
Try building a cutsom SVG component like this:

https://codesandbox.io/s/dreamy-joana-13ij6o?file=/src/App.js

2023-01-25 14:10 UTC, SaschaRadojkovic commented on pages/details/[id].js
> +          console.log(tutorial);
here is a console.log yet

2023-01-25 14:13 UTC, merged